---
name: Build dsv e-commerce app
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy e-commerce app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Deploy
        run: npm run deploy
